api_platform:
    mapping:
        paths: 
            -  '%kernel.project_dir%/src/Concerts/Domain/Entity/' # Modèles (entités) dans Domain/
            -  '%kernel.project_dir%/src/Alert/Domain/Entity/' 
            -  '%kernel.project_dir%/src/Markers/Domain/Entity/' 
            -  '%kernel.project_dir%/src/Contact/Domain/Entity/'
            -  '%kernel.project_dir%/src/Sponsors/Domain/Entity/'
            -  '%kernel.project_dir%/src/Customers/Domain/Entity/'
        
    #patch_formats:
        #json: ['application/merge-patch+json']
    formats:        
        json: ['application/json']   
        jsonld: ['application/ld+json']    
    defaults:
        pagination_enabled: true
        pagination_items_per_page: 50
        pagination_maximum_items_per_page: 50
        stateless: false
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
        normalization_context:
            groups: 
                -  ['concerts']
                -  ['alert']
                -  ['markers']
                -  ['contact']
                -  ['sponsors']
                -  ['customers']
                
        denormalization_context:
            groups: 
                -  ['concerts']
                -  ['alert']
                -  ['markers']
                -  ['contact']
                -  ['sponsors']
                -  ['customers']

    exception_to_status:
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400
        App\Application\Exception\NotFoundException: 404
        App\Application\Exception\UnauthorizedException: 401


    