api_platform:
    formats:
      jsonld: ['application/ld+json']
      json: ['application/json']
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']


