api_platform:
    formats:
      json: ['application/json']
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']


when@prod:
  api_platform:
    # enable_docs: false
    enable_entrypoint: false
    enable_swagger_ui: false