doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '10.5.26-MariaDB'  # ← remplace avec la vraie version détectée
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
# pour architecture en couche: mapping dans les répertoire Domain/Entity
            Concert:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Concerts/Domain/Entity'
                prefix: 'App\Concerts\Domain\Entity'
                alias: Concert

            Alert:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Alert/Domain/Entity'
                prefix: 'App\Alert\Domain\Entity'
                alias: Alert

            Marker:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Markers/Domain/Entity'
                prefix: 'App\Markers\Domain\Entity'
                alias: Marker

            Users:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Users/Domain/Entity'
                prefix: 'App\Users\Domain\Entity'
                alias: Users
            
            Contact:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Contact/Domain/Entity'
                prefix: 'App\Contact\Domain\Entity'
                alias: Contact

            Sponsor:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Sponsors/Domain/Entity'
                prefix: 'App\Sponsors\Domain\Entity'
                alias: Sponsor
            
         




        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
