vich_uploader:   
    db_driver: orm
    mappings:
        concerts:
            uri_prefix: /uploads/concerts/
            upload_destination: '%kernel.project_dir%/public/uploads/concerts/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
             
      
        
        
