vich_uploader:   
    db_driver: orm
    mappings:
        concerts:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
             
      
        
        
