.PHONY: tests
tests:
	php bin/console d:d:d --force --if-exists --env=test      // supprimer la base de données si elle existe
	php bin/console d:d:c --env=test                          // Créer la base de donnée
	php bin/console d:m:m --no-interaction --env=test         // Migrer les migrations
	php bin/console d:f:l --np-interaction --env=test         // Charger les fixtures
	php bin/phpunit --testdox tests/Unit/                     // Faire les tests unitaires
	php bin/phpunit --testdox tests/Functional/               // Faire les test fonctionnels



.PHONY: deploy
deploy: ##Deployment tasks
	composer install --optimize-autoloader
	php bin/console doctrine:database:create --if-not-exist
	php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migrations
	php bin/console cache:clear --env=prod