marker.detail:
  path: /marker/{id}
  controller: App\Markers\UI\Controller\MarkerController::detail
  requirements:
    id: '\d+'
  methods: [GET]

marker.edit:
  path: /marker/edit/{id}
  controller: App\Markers\UI\Controller\MarkerController::saveMarker
  defaults:
    id: 0
  methods: [GET, POST]

marker.delete:
  path: /marker/delete/{id}
  controller: App\Markers\UI\Controller\MarkerController::delete
  methods: [DELETE]

marker.list.filtered:
  path: /marker/filtered
  controller: App\Markers\UI\Controller\MarkerController::indexFiltered  
  methods: [GET]

