sponsor.list.filtered:
  path: /sponsor/filtered
  controller: App\Sponsors\UI\Controller\SponsorController::indexFiltered  
  methods: [GET]

sponsor.detail:
  path: /sponsor/{id}
  controller: App\Sponsors\UI\Controller\SponsorController::detail
  requirements:
    id: '\d+'
  methods: [GET]

sponsor.edit:
  path: /sponsor/edit/{id}
  controller: App\Sponsors\UI\Controller\SponsorController::saveSponsor
  defaults:
    id: 0
  methods: [GET, POST]

sponsor.delete:
  path: /sponsor/delete/{id}
  controller: App\Sponsors\UI\Controller\SponsorController::delete
  methods: [DELETE]
