name: deploy

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: execute ssh command
              uses: appleboy/ssh-action@v1.2.1
              with:
                host:  ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.KEY_IONOS }}
                script: |
                    cd ~/LiveEventsBackEnd
                    git pull origin main --rebase
                    sudo npm install
                    sudo composer install --optimize-autoloader
                    php bin/console doctrine:database:create --if-not-exist
                    php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migrations
                    php bin/console cache:clear --env=prod
                    
                    
                   
                    

