name: deploy

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: execute ssh command
              uses: appleboy/ssh-action@v1.2.1
              with:
                host:  ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.KEY_IONOS }}
                script: |
                    cd /var/www/LiveEventsBackEnd
                    git pull origin main 
                    composer install --optimize-autoloader
                    php bin/console cache:clear --env=prod
                    cd /var/www/LiveEventsBackEnd/public
                    ls
                    
                    
                   
                    

