name: deploy

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: execute ssh command
              uses: appleboy/ssh-action@v1.2.1
              with:
                host:  ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PWD }}
                fingerprint: SHA256:TvrGYSwNIKR1WW/1hYH7967mIz5FP1K51XW8OgNO6JU
                script: |
                    cd www
                    git clone git@github.com:arndelp/LiveEventsBackEnd.git 
                    ls
                    
                   
                    

