name: deploy

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: execute ssh command
              uses: appleboy/ssh-action@v1.2.1
              with:
                host:  ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_PWD }}
                key: 6c:a2:f5:6c:92:01:c5:e3:d6:f7:09:a5:d8:ab:8e:4c
                script: |
                    cd www
                    git clone git@github.com:arndelp/LiveEventsBackEnd.git 
                    ls
                    
                   
                    

