name: deploy

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: execute ssh command
              uses: appleboy/ssh-action@v1.2.1
              with:
                host:  ssh-sushi.alwaysdata.net
                username: sushi
                password: Sushi2306%
                script: |
                    cd ~/www
                    git pull origin main --rebase
                    make deploy
                    

